=== mackandelius/OpenFlight-VRC/Packages/com.mattshark.openflight/Runtime/data_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "JSON Version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
      "description": "The version of the current JSON. The minor version should be incremented when a new avatar is added"
    },
    "JSON Date": {
      "type": "string",
      "format": "date",
      "pattern": "^(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$",
      "description": "The date of the current JSON. The date should be updated when this file is changed at all"
    },
    "Contributers": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A VRChat username"
      },
      "description": "A list of all the people who have contributed to this JSON file. The strings listed are all VRChat usernames"
    },
    "Bases": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "title": "Avatar Base",
        "description": "An avatar base that is eligible for auto detection",
        "additionalProperties": {
          "type": "object",
          "title": "Avatar Base Variant",
          "description": "A variant of an avatar base that is eligible for auto detection. This allows grouping multiple avatar revisions into a single base.",
          "properties": {
            "Name": {
              "type": "string",
              "description": "The name of the avatar base variant"
            },
            "Creator": {
              "type": "string",
              "description": "The creator of the avatar base variant"
            },
            "Introducer": {
              "type": "string",
              "description": "The VRChat username of the person who introduced the avatar base variant to the JSON file. This is used to track who added what to the JSON file."
            },
            "Hash": {
              "type": "array",
              "description": "The hash of the avatar base variant. This is used to identify the avatar base variant in game",
              "items": {
                "type": "string",
                "pattern": "^-?[0-9]{1,}v2",
                "not": {
                  "$comment": "This is cursed, but its the only way to comment what each hash goes with each avatar thats excluded",
                  "enum": [
                    "Wickerbeast",
                    "782623496v2",
                    "Nardoragon",
                    "341832v2",
                    "Tigerbee",
                    "-657973745v2",
                    "Rexioum",
                    "10151625v2",
                    "Fennix",
                    "608546079v2",
                    "Hobkin",
                    "776808177v2",
                    "Aqualux",
                    "-268831991v2",
                    "Awtter",
                    "482781345v2",
                    "Dergadol",
                    "-1320032328v2",
                    "Kibby",
                    "-1658919646v2",
                    "Mantled Beast",
                    "-2138640187v2",
                    "Protodal",
                    "998558977v2",
                    "Protoroo",
                    "-180659171v2",
                    "Rikorchi",
                    "943490728v2",
                    "Silvalux",
                    "463788516v2",
                    "Taidum",
                    "328210781v2",
                    "Zurg",
                    "-1254610910v2",
                    "Maelstrorca",
                    "253114771v2",
                    "Freakhound",
                    "-2048057485v2",
                    "Novabeast",
                    "216280090v2",
                    "Shiba Inu",
                    "1227029313v2",
                    "Spirit",
                    "-1486304379v2",
                    "Draconis",
                    "261301392v2",
                    "Slugcat",
                    "-2089283505v2",
                    "Saekin",
                    "-81961577v2",
                    "Leafygote",
                    "1291380117v2",
                    "Drax",
                    "-1082171690v2",
                    "Rikku",
                    "975948034v2",
                    "Mixamo armature ca 2018",
                    "-416877898v2",
                    "The Old Nanachi",
                    "-799929667v2"
                  ]
                }
              },
              "minItems": 1
            },
            "Weight": {
              "type": "number",
              "description": "The weight the avatar should have in game. This is currently unused."
            },
            "WingtipOffset": {
              "type": "number",
              "description": "The wingtip offset of the avatar."
            }
          },
          "required": [
            "Name",
            "Creator",
            "Introducer",
            "Hash",
            "Weight",
            "WingtipOffset"
          ],
          "additionalProperties": false
        },
        "minProperties": 1
      },
      "minProperties": 1,
      "description": "All of the Unique avatar bases that are eligible for auto detection"
    }
  },
  "required": [
    "JSON Version",
    "JSON Date",
    "Bases"
  ]
}

=== mackandelius/OpenFlight-VRC/Packages/com.mattshark.openflight/Runtime/data.json
{
  "$schema": "./data_schema.json",
  "JSON Version": "2.74.0",
  "JSON Date": "2026-04-22",
  "Contributers": [
    "ItsFloofy",
    "Daernaro",
    "Darizard",
    "DatGek",
    "gardwolf",
    "Happyrobot33",
    "Heather May",
    "Igneoun",
    "IlChiporiAlbino",
    "Krazen",
    "Literally Marty",
    "Mattshark89",
    "Morghus",
    "NTM3193",
    "OrcaToaster",
    "Roimu",
    "Slash0x",
    "fundale",
    "mackandelius",
    "Eglantine",
    "~EmberVR~",
    "Nanireid101",
    "Mіcca",
    "FunnelVision",
    "PhoenixFallen",
    "-Dark-Spirit-",
    "Mike Da Bird",
    "dasnull",
    "Polaris°",
    "Glowva",
    "Purpzie",
    "a distraction",
    "InvertedCrink",
    "~Angiethekirin~",
    "Kitsune KAZE",
    "Luna Neszy",
    "Reazy Fluff",
    "Tokyozilla",
    "SandFoxed",
    "BurnsToShine",
    "Mama_TeraByte",
    "Lane_the_Rex",
    "ＶｉｘｅｎＤａｖａｌｉ",
    "Toys0125",
    "hantnor",
    "NeoSnivy",
    "ArkeoTP",
    "SkyWarrior",
    "Apache Longbow",
    "Ordinary_night",
    "a distraction",
    "Mieze",
    "TrueHiddenS",
    "S e n t i n e l",
    "Iced_lem0n",
    "Jafira-Dragon",
    "NoodleTheAvali",
    "LunaFree",
    "Dream_LP",
    "AeolusDraco",
    "WingHugs",
    "Zero_assasin",
    "Talii-bit",
    "FlorianGrille",
    "Woffle Nibbler",
    "WebserferOwO",
    "Zeimyth",
    "Fluxsynth",
    "wordweaver1001",
    "KUROPPER",
    "Xavarius",
    "Katislove"
  ],
  "Bases": {
    "Kitavali": {
      "Original": {
        "Name": "Kitavali",
        "Creator": "Rai Kitamatsu",
        "Introducer": "Happyrobot33",
        "Hash": [
          "234133961v2"
        ],
        "Weight": 1,
        "WingtipOffset": 6.6
      },
        "Weaver": {
        "Name": "Kitachi",
        "Creator": "Rai Kitamatsu/Rantis",
        "Introducer": "wordweaver1001",
        "Hash": [
          "-1331949987v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0
      }
    },
    "Batdal": {
      "Original": {
        "Name": "Batdal",
        "Creator": "Nicoreda",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1977644388v2"
        ],
        "Weight": 1,
        "WingtipOffset": 5.0
      },
      "V2": {
        "Name": "Batdal",
        "Creator": "Nicoreda",
        "Introducer": "Kitsune KAZE",
        "Hash": [
          "676162765v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.8
      }
    },
    "Chimera Recon": {
      "Original": {
        "Name": "Chimera Recon",
        "Creator": "Lackofbindings",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1196345180v2"
        ],
        "Weight": 1,
        "WingtipOffset": 1.0
      }
    },
    "Jerry": {
      "Original": {
        "Name": "Jerry [Avali]",
        "Creator": "Rai Kitamatsu",
        "Introducer": "Happyrobot33",
        "Hash": [
          "1324149349v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.05
      },
      "Toys Jerry": {
        "Name": "Toys Jerry",
        "Creator": "Toys0125 / Rai Kitamatsu",
        "Introducer": "Toys0125",
        "Hash": [
          "1109002599v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.05
      },
      "Miezes Jerry Avali": {
        "Name": "Miezes Jerry Avali",
        "Creator": "Rai Kitamatsu / Mieze",
        "Introducer": "Mieze",
        "Hash": [
          "-1517578892v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.05
      }
    },
    "Rosa'vali": {
      "Original": {
        "Name": "Rosa'vali",
        "Creator": "Rosebur",
        "Introducer": "Happyrobot33",
        "Hash": [
          "1582207921v2"
        ],
        "Weight": 1,
        "WingtipOffset": 3
      }
    },
    "Chibi Avali": {
      "Original": {
        "Name": "Chibi Avali",
        "Creator": "【Pͦoͭlͭyͬ】",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-277689357v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Aerogen": {
      "Original": {
        "Name": "Aerogen",
        "Creator": "Rosebur",
        "Introducer": "Happyrobot33",
        "Hash": [
          "1189110379v2"
        ],
        "Weight": 1,
        "WingtipOffset": 2.0
      }
    },
    "Royal Avali": {
      "Original": {
        "Name": "Royal Avali",
        "Creator": "Octupus King",
        "Introducer": "Happyrobot33",
        "Hash": [
          "1819772288v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Minecraft Avali": {
      "Original": {
        "Name": "Minecraft Avali",
        "Creator": "K_Reshi",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-137572979v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Mechanical Avali": {
      "Original": {
        "Name": "Mechanical Avali",
        "Creator": "AngriestSCV",
        "Introducer": "Happyrobot33",
        "Hash": [
          "666213272v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "BotVali": {
      "Original": {
        "Name": "BotVali",
        "Creator": "Sillurgy",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1152420328v2"
        ],
        "Weight": 1,
        "WingtipOffset": 1.0
      }
    },
    "Pooltoy Avali": {
      "Original": {
        "Name": "Pooltoy Avali",
        "Creator": "ModernBalloonie",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-5390243v2"
        ],
        "Weight": 1,
        "WingtipOffset": 2.7
      }
    },
    "Pooltoy Da'vali": {
      "Original": {
        "Name": "Pooltoy Da'vali",
        "Creator": "Maitake Inu",
        "Introducer": "Happyrobot33",
        "Hash": [
          "2014277989v2"
        ],
        "Weight": 1,
        "WingtipOffset": 1.54
      }
    },
    "Da'vali": {
      "Original": {
        "Name": "Da'vali",
        "Creator": "Rai Kitamatsu",
        "Introducer": "Mattshark89",
        "Hash": [
          "-1463139696v2"
        ],
        "Weight": 1,
        "WingtipOffset": 1.7
      }
    },
    "Javali": {
      "Original": {
        "Name": "Javali",
        "Creator": "Javenchi",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-441892162v2"
        ],
        "Weight": 1,
        "WingtipOffset": 3.0
      },
      "JaReverse": {
        "Name": "JaReverse",
        "Creator": "Webserfer / Javenchi / VictonRoy",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1169853867v2"
        ],
        "Weight": 1,
        "WingtipOffset": 3.3
      },
      "Javali Modif": {
        "Name": "Javali Modif",
        "Creator": "Javenchi / Webserfer",
        "Introducer": "SkyWarrior",
        "Hash": [
          "-525410190v2"
        ],
        "Weight": 1,
        "WingtipOffset": 3.0
      }
    },
    "Nexa'vali": {
      "Original": {
        "Name": "Nexa'vali",
        "Creator": "Angelboy",
        "Introducer": "Happyrobot33",
        "Hash": [
          "293252502v2",
          "1042603441v2",
          "-1520979602v2"
        ],
        "Weight": 1,
        "WingtipOffset": 2.7
      },
      "Nexa'vali v4": {
        "Name": "Nexa'vali",
        "Creator": "Angelboy",
        "Introducer": "NeoSnivy",
        "Hash": [
          "686616116v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.2
      },
      "Mamma Nexa'vali": {
        "Name": "Mamma Nexa'vali",
        "Creator": "Angelboy / 989onan",
        "Introducer": "NeoSnivy",
        "Hash": [
          "-2104754549v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.2
      }
    },
    "Seeker Avali": {
      "Original": {
        "Name": "Seeker Avali",
        "Creator": "Star-Max",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-860693031v2"
        ],
        "Weight": 1,
        "WingtipOffset": 8.0
      }
    },
    "Lorc'Avali": {
      "Original": {
        "Name": "Lorc'Avali",
        "Creator": "LocanTheAvali",
        "Introducer": "Happyrobot33",
        "Hash": [
          "1900199170v2"
        ],
        "Weight": 1,
        "WingtipOffset": 7.1
      }
    },
    "Nuk'Vali": {
      "Original": {
        "Name": "Nuk'Vali",
        "Creator": "Nukude",
        "Introducer": "Happyrobot33",
        "Hash": [
          "917941807v2"
        ],
        "Weight": 1,
        "WingtipOffset": 5.6
      }
    },
    "NatVali": {
      "Original": {
        "Name": "NatVali",
        "Creator": "Natval",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-672767444v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Reverse NatVali": {
      "Original": {
        "Name": "Reverse NatVali",
        "Creator": "Natval",
        "Introducer": "Happyrobot33",
        "Hash": [
          "687939090v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Reverse Avali": {
      "Original": {
        "Name": "Reverse Avali",
        "Creator": "VictonRoy",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1678847866v2"
        ],
        "Weight": 1,
        "WingtipOffset": 1.3
      },
      "Modified": {
        "Name": "Reverse Avali",
        "Creator": "VictonRoy / farfelu",
        "Introducer": "Heather May",
        "Hash": [
          "-1731617419v2"
        ],
        "Weight": 1,
        "WingtipOffset": 2.28
      },
      "Webserfer Alteration": {
        "Name": "Reverse Avali",
        "Creator": "VictonRoy / Webserfer",
        "Introducer": "Webserfer",
        "Hash": [
          "-597043440v2"
        ],
        "Weight": 1,
        "WingtipOffset": 4.5
      }
    },
    "EVA Avali": {
      "Original": {
        "Name": "EVA Avali",
        "Creator": "Frownytown",
        "Introducer": "Happyrobot33",
        "Hash": [
          "-1365888474v2"
        ],
        "Weight": 1,
        "WingtipOffset": 0.0
      }
    },
    "Corvali": {
      "Original": {
